export const States = [
  {
    code: "001",
    name: "ABIA",
    country: "NIGERIA",
    geo_code: "SE",
  },
  {
    code: "002",
    name: "ADAMAWA",
    country: "NIGERIA",
    geo_code: "NE",
  },
  {
    code: "003",
    name: "AKWA-IBOM",
    country: "NIGERIA",
    geo_code: "SS",
  },
  {
    code: "004",
    name: "ANAMBRA",
    country: "NIGERIA",
    geo_code: "SE",
  },
  {
    code: "005",
    name: "BAUCHI",
    country: "NIGERIA",
    geo_code: "NE",
  },
  {
    code: "006",
    name: "BENUE",
    country: "NIGERIA",
    geo_code: "NC",
  },
  {
    code: "007",
    name: "BORNO",
    country: "NIGERIA",
    geo_code: "NE",
  },
  {
    code: "008",
    name: "CROSS-RIVER",
    country: "NIGERIA",
    geo_code: "SS",
  },
  {
    code: "009",
    name: "DELTA",
    country: "NIGERIA",
    geo_code: "SS",
  },
  {
    code: "010",
    name: "EDO",
    country: "NIGERIA",
    geo_code: "SS",
  },
  {
    code: "011",
    name: "ENUGU",
    country: "NIGERIA",
    geo_code: "SE",
  },
  {
    code: "012",
    name: "IMO",
    country: "NIGERIA",
    geo_code: "SE",
  },
  {
    code: "013",
    name: "JIGAWA",
    country: "NIGERIA",
    geo_code: "NW",
  },
  {
    code: "014",
    name: "KADUNA",
    country: "NIGERIA",
    geo_code: "NW",
  },
  {
    code: "015",
    name: "KANO",
    country: "NIGERIA",
    geo_code: "NW",
  },
  {
    code: "016",
    name: "KATSINA",
    country: "NIGERIA",
    geo_code: "NW",
  },
  {
    code: "017",
    name: "KEBBI",
    country: "NIGERIA",
    geo_code: "NW",
  },
  {
    code: "018",
    name: "KOGI",
    country: "NIGERIA",
    geo_code: "NC",
  },
  {
    code: "019",
    name: "KWARA",
    country: "NIGERIA",
    geo_code: "NC",
  },
  {
    code: "020",
    name: "LAGOS",
    country: "NIGERIA",
    geo_code: "SW",
  },
  {
    code: "021",
    name: "NIGER",
    country: "NIGERIA",
    geo_code: "NC",
  },
  {
    code: "022",
    name: "OGUN",
    country: "NIGERIA",
    geo_code: "SW",
  },
  {
    code: "023",
    name: "ONDO",
    country: "NIGERIA",
    geo_code: "SW",
  },
  {
    code: "024",
    name: "OSUN",
    country: "NIGERIA",
    geo_code: "SW",
  },
  {
    code: "025",
    name: "OYO",
    country: "NIGERIA",
    geo_code: "SW",
  },
  {
    code: "026",
    name: "PLATEAU",
    country: "NIGERIA",
    geo_code: "NC",
  },
  {
    code: "027",
    name: "RIVERS",
    country: "NIGERIA",
    geo_code: "SS",
  },
  {
    code: "028",
    name: "SOKOTO",
    country: "NIGERIA",
    geo_code: "NW",
  },
  {
    code: "029",
    name: "TARABA",
    country: "NIGERIA",
    geo_code: "NE",
  },
  {
    code: "030",
    name: "YOBE",
    country: "NIGERIA",
    geo_code: "NE",
  },
  {
    code: "031",
    name: "FCT-ABUJA",
    country: "NIGERIA",
    geo_code: "NC",
  },
  {
    code: "032",
    name: "BAYELSA",
    country: "NIGERIA",
    geo_code: "SS",
  },
  {
    code: "033",
    name: "EBONYI",
    country: "NIGERIA",
    geo_code: "SE",
  },
  {
    code: "034",
    name: "EKITI",
    country: "NIGERIA",
    geo_code: "SW",
  },
  {
    code: "035",
    name: "GOMBE",
    country: "NIGERIA",
    geo_code: "NE",
  },
  {
    code: "036",
    name: "NASARAWA",
    country: "NIGERIA",
    geo_code: "NC",
  },
  {
    code: "037",
    name: "ZAMFARA",
    country: "NIGERIA",
    geo_code: "NW",
  },
];
